# Generated by Django 5.1.6 on 2025-02-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_email_order_payment_method_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
