# Generated by Django 5.1.6 on 2025-03-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
