services:
  - type: web
    name: ecommerce
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-%t$fg*(28f(9a@(#bhlxp*5*98c$zwmtpmshy&0qk8-n9mos#7
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
